export type RestaurantDirectoryEntry = {
  id: string;
  name: string;
  address: string;
  operatorId: string;
  operatorName: string;
  aliases?: string[];
};

export const restaurantDirectory: RestaurantDirectoryEntry[] = [
  { id: "236", name: "Энгельса 21", address: "Энгельса 21", operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "875269", name: "Энгельса 154 (ТЦ Гранд Каньон)", address: "Энгельса 154 (ТЦ Гранд Каньон)", operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "222", name: "Просвещения 32", address: "Просвещения 32", operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "275", name: "Галерная 26", address: "Галерная 26", aliases: ["Труда пл., 3"], operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "214", name: "Сестрорецк, Приморское 348", address: "Сестрорецк, Приморское 348", operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "869805", name: "Савушкина 141 (ТЦ Меркурий)", address: "Савушкина 141 (ТЦ Меркурий)", operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "645322", name: "Большая Конюшенная 10", address: "Большая Конюшенная 10", operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "306", name: "Б.Морская 13", address: "Б.Морская 13", operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "237", name: "Крестовский 24", address: "Крестовский 24", operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "1663583", name: "Мурино, ул. Екатерининская 17", address: "Мурино, ул. Екатерининская 17", operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "234", name: "Комендантский 13", address: "Комендантский 13", operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "240", name: "Пискаревский 25", address: "Пискаревский 25", operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "230", name: "Гражданский 116", address: "Гражданский 116", operatorId: "ekaterina-vasilievna", operatorName: "Екатерина Васильевна" },
  { id: "300", name: "Московский 222", address: "Московский 222", operatorId: "olga-igorevna", operatorName: "Ольга Игоревна" },
  { id: "260", name: "Кронверкский 13", address: "Кронверкский 13", operatorId: "olga-igorevna", operatorName: "Ольга Игоревна" },
  { id: "1797119", name: "Большой ПС 14", address: "Большой ПС 14", operatorId: "olga-igorevna", operatorName: "Ольга Игоревна" },
  { id: "314", name: "Пулковское 25 (ТЦ Лето)", address: "Пулковское 25 (ТЦ Лето)", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "224", name: "Энгельса 134", address: "Энгельса 134", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "307", name: "Славы 43", address: "Славы 43", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "645326", name: "Итальянская 29", address: "Итальянская 29", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "283", name: "Белы Куна 3 (ТРК Международный)", address: "Белы Куна 3 (ТРК Международный)", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "268", name: "Владимирский 14", address: "Владимирский 14", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "228", name: "Просвещения 78", address: "Просвещения 78", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "318", name: "Грибоедова 22", address: "Грибоедова 22", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "1039378", name: "Большевиков 18", address: "Большевиков 18", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "298", name: "Индустриальный 26", address: "Индустриальный 26", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "503", name: "Выборг, Ленинградский 29", address: "Выборг, Ленинградский 29", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "238", name: "Черной речки наб 51", address: "Черной речки наб 51", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "3670", name: "Новаторов 32", address: "Новаторов 32", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "1457827", name: "Чернышевского, 10", address: "Чернышевского, 10", aliases: ["Захарьевская ул., 27"], operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "839130", name: "Невский 42", address: "Невский 42", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "292", name: "Заневский 67", address: "Заневский 67", operatorId: "natalia-andreevna", operatorName: "Наталья Андреевна" },
  { id: "278", name: "Фучика 2 (ТРК Рио)", address: "Фучика 2 (ТРК Рио)", operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "801338", name: "Ефимова 2 (ТК Пик)", address: "Ефимова 2 (ТК Пик)", operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "741759", name: "Заневский 71 (ДК)", address: "Заневский 71 (ДК)", operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "327", name: "Колпино, Октябрьская 8", address: "Колпино, Октябрьская 8", operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "269", name: "Московский 145", address: "Московский 145", operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "142183", name: "Брантовская дорога 3 (ТРК Охта-Молл)", address: "Брантовская дорога 3 (ТРК Охта-Молл)", aliases: ["Якорная ул., 5А (ТРЦ Охта Молл)"], operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "295", name: "Московский 195", address: "Московский 195", operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "311", name: "Балканская 5", address: "Балканская 5", operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "137979", name: "Кудрово, Европейский 8", address: "Кудрово, Европейский 8", operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "1308568", name: "Мурманское 12 (Мега Дыбенко)", address: "Мурманское 12 (Мега Дыбенко)", operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "1153645", name: "Московский 157", address: "Московский 157", operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "325", name: "Гатчина, 25 октября 59", address: "Гатчина, 25 октября 59", operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "289", name: "Загородный 64", address: "Загородный 64", operatorId: "valeria-anatolievna", operatorName: "Валерия Анатольевна" },
  { id: "215", name: "Кронштадт, Ленина 31", address: "Кронштадт, Ленина 31", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "313", name: "Грибоедова 10", address: "Грибоедова 10", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "282", name: "Лиговский 93", address: "Лиговский 93", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "266", name: "Жуковского 36", address: "Жуковского 36", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "502", name: "Приозерск, Калинина 11", address: "Приозерск, Калинина 11", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "645308", name: "Каменноостровский 44", address: "Каменноостровский 44", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "258", name: "Ленинский 95", address: "Ленинский 95", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "324", name: "Красное Село, Ленина 51", address: "Красное Село, Ленина 51", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "320", name: "Ломоносов, Красноармейская 19 (ТК Рамбов)", address: "Ломоносов, Красноармейская 19 (ТК Рамбов)", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "1709622", name: "Славянка, ул. Ростовская, д. 20, стр. 1", address: "Славянка, ул. Ростовская, д. 20, стр. 1", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "888767", name: "Петергофское 51 (Жемчужная Плаза)", address: "Петергофское 51 (Жемчужная Плаза)", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "323", name: "Пушкин, Октябрьский 7", address: "Пушкин, Октябрьский 7", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "1074699", name: "6 линия ВО 17", address: "6 линия ВО 17", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
  { id: "263", name: "Стачек 99 (ТРК Континент)", address: "Стачек 99 (ТРК Континент)", operatorId: "marina-evgenievna", operatorName: "Марина Евгеньевна" },
];